name: Publish Refresh-actor
on:
  workflow_dispatch:

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: publish
        uses: anton-nagornyi/anyit-auth/.github/composite-actions/publish@main
        with:
          working-directory: packages/refresh-actor
          npm-auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
